### ISSUE TITLE
minecraft 1.19.2 not launching

### ISSUE THREAD

**Issue by Aleksanaa** [Admicos/minecraft-wayland#37] opened 2022-12-13 18:18 UTC
```
---- Minecraft Crash Report ----
// Why is it breaking :(
Time: 2022-12-14 02:15:35
Description: Initializing game
java.lang.ExceptionInInitializerError
	at org.lwjgl.glfw.GLFW.nglfwGetError(GLFW.java:1219)
	at org.lwjgl.glfw.GLFW.glfwGetError(GLFW.java:1248)
	at dzu.a(SourceFile:140)
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:59)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:826)
	at efu.<init>(SourceFile:481)
	at net.minecraft.client.main.Main.a(SourceFile:205)
	at net.minecraft.client.main.Main.main(SourceFile:51)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.NullPointerException: A required function is missing: glfwInitAllocator
	at org.lwjgl.system.APIUtil.requiredFunctionMissing(APIUtil.java:129)
	at org.lwjgl.system.APIUtil.apiGetFunctionAddress(APIUtil.java:122)
	at org.lwjgl.glfw.GLFW$Functions.<clinit>(GLFW.java:42)
	... 15 more
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at org.lwjgl.glfw.GLFW.nglfwGetError(GLFW.java:1219)
	at org.lwjgl.glfw.GLFW.glfwGetError(GLFW.java:1248)
	at dzu.a(SourceFile:140)
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:59)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:826)
	at efu.<init>(SourceFile:481)
-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.a(SourceFile:205)
	at net.minecraft.client.main.Main.main(SourceFile:51)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)
-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 6.0.11-zen1-1.1-zen
	Java Version: 19.0.1, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 938964688 bytes (895 MiB) / 2487222272 bytes (2372 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800H with Radeon Graphics
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Cezanne [Radeon Vega Series / Radeon Vega Mobile Series]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 258.00
	Graphics card #0 deviceId: 0x1638
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 35526.46
	Virtual memory used (MB): 7802.58
	Swap memory total (MB): 28606.00
	Swap memory used (MB): 10.03
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	Launched Version: 1.19.2
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	CPU: <unknown>
```

**Comment by JamiKettunen** [comment] 2022-12-13 18:36
Duplicate of both #25 and #36, use [the `one-nineteen`](https://github.com/Admicos/minecraft-wayland/tree/one-nineteen) branch. See also #35.

**Closed** 2022-12-15 05:34 UTC
